### ISSUE TITLE
BSOD on boot in NDIS.sys

### ISSUE THREAD

**Issue by JonathonReinhart** [YanVugenfirer/kvm-guest-drivers-windows#28]
Several times I've seen a crash in NDIS.sys at boot - before the login screen is even shown.  I have to assume this is the VirtIO Ethernet driver.  I believe I also saw a similar BSOD when I first tried to load the driver.

Unfortunately, for some reason, no minidump is generated, even though the system is configured to do so. Also, this bug is not easily reproduced.  I'll leave this bug open as a reminder, and a place to record any findings.

**Comment by YanVugenfirer** [comment]
Hi Jonathon,

What driver version are you using? We had some unstable release due to the
work done on multi-queue feature.


Best regards,
Yan.

On Tue, Jan 6, 2015 at 8:39 AM, Jonathon Reinhart <notifications@github.com>
wrote:

> Several times I've seen a crash in NDIS.sys at boot - before the login
> screen is even shown. I have to assume this is the VirtIO Ethernet driver.
> I believe I also saw a similar BSOD when I first tried to load the driver.
>
> Unfortunately, for some reason, no minidump is generated, even though the
> system is configured to do so. Also, this bug is not easily reproduced.
> I'll leave this bug open as a reminder, and a place to record any findings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/28>.
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by JonathonReinhart** [comment]
I'm using the latest release, 0.1-94, or RedHat 61.71.104.9400

**Comment by YanVugenfirer** [comment]
Commit
https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/b07fe167f53e03628c18772ec51b1d5dccce948c
fixed this problem right after 94 was released.



On Tue, Jan 6, 2015 at 9:46 AM, Jonathon Reinhart <notifications@github.com>
wrote:

> I'm using the latest release, 0.1-94, or RedHat 61.71.104.9400
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/28#issuecomment-68835705>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by JonathonReinhart** [comment]
It appears that I just picked a bad time to start playing with Windows 7 on KVM then :-)
I'll close this and wait for the next release.

**Comment by YanVugenfirer** [comment]
There is a stable version without multi-queue:

http://alt.fedoraproject.org/pub/alt/virtio-win/stable/

Please use it.

On Tue, Jan 6, 2015 at 11:07 AM, Jonathon Reinhart <notifications@github.com
> wrote:

> It appears that I just picked a bad time to start playing with Windows 7
> on KVM then :-)
> I'll close this and wait for the next release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/28#issuecomment-68841637>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com
