### ISSUE TITLE
When the number of queues less than number of vcpus, networking is not stable.

### ISSUE THREAD

**Issue by geekben** [YanVugenfirer/kvm-guest-drivers-windows#29]
Hi Yan,

During the performance testing of multiqueue for NetKVM, I found that when the number of queues is less than number of vcpus (2 queue, 4 vcpu), the networking connection of VM will fail to work under a big pressure by receiving multiple netperf streams simultaneously. Meanwhile, under this case, disable virtio-net device or change the RSS related parameters of the virtio-net device will make device manager hang. I think this may be a bug.

VM OS: windows server 2008 R2 standard
virtio-driver: win7_amd64 netkvm built from the latest code.

Best regards,
Ben.

**Comment by YanVugenfirer** [comment]
Yossi - please take a look.

On Tue, Jan 6, 2015 at 10:00 AM, Ben <notifications@github.com> wrote:

> Hi Yan,
>
> During the performance testing of multiqueue for NetKVM, I found that when
> the number of queues is less than number of vcpus (2 queue, 4 vcpu), the
> networking connection of VM will fail to work under a big pressure by
> receiving multiple netperf streams simultaneously. Meanwhile, under this
> case, disable virtio-net device or change the RSS related parameters of the
> virtio-net device will make device manager hang. I think this may be a bug.
>
> VM OS: windows server 2008 R2 standard
> virtio-driver: win7_amd64 netkvm built from the latest code.
>
> Best regards,
> Ben.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/29>.
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by YanVugenfirer** [comment]
Hi,

Did you tried latest stable code ?

Thanks,
Yan.

**Comment by YanVugenfirer** [comment]
Fixed by the following commit: https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/3236107f91741899e22d4db0aacb2be702558690

**Comment by jhindin** [comment]
The bug is apparently fixed with commit https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/3236107f91741899e22d4db0aacb2be702558690
