### ISSUE TITLE
Netkvm in vista/x86 from virtio-win-0.1-94.iso can't work

### ISSUE THREAD

**Issue by geekben** [YanVugenfirer/kvm-guest-drivers-windows#31]
Hi Yan,

I tried to install the netkvm virtio driver to a 32bit windows server 2008 with virtio-win-0.1-94.iso, but it will yield code 10 error. virtio-win-0.1-81.iso works!

Best regards,
Ben

**Comment by YanVugenfirer** [comment]
Hi Ben,

We treat all the builds until virtio-win-0.1-100 as experimental and unstable. I suggest to try the latest one. 

Will check if we released it.

Best regards,
Yan.

**Comment by YanVugenfirer** [comment]
Hi Ben,

Build 100 is released:
http://alt.fedoraproject.org/pub/alt/virtio-win/latest/images/bin/

Best regards,
Yan.

**Comment by geekben** [comment]
Got it!

Thanks,
Ben
