### ISSUE TITLE
Bump version number in vioscsi/buildAll.bat when doing a release

### ISSUE THREAD

**Issue by cpatulea** [YanVugenfirer/kvm-guest-drivers-windows#32]
Would it be possible to occasionally update the _RHEL_RELEASE_VERSION_, _BUILD_MAJOR_VERSION_, _BUILD_MINOR_VERSION_ in vioscsi/buildAll.bat when doing a release?

The source, without any special environment variables, appears to build version "62.61.101.58000". The latest binary releases from this location:
http://alt.fedoraproject.org/pub/alt/virtio-win/latest/images/

..have version "62.71.104.10000".

I guess in your usual release process you set _RHEL_RELEASE_VERSION_ etc. in the environment before building?

It's not necessary to update the version very often, just every release would be ok, so we can translate from binary version to approximate source version.

**Comment by YanVugenfirer** [comment]
Hi,

Thanks for the suggestion. We might start doing this.

For now the way to figure the source for specific release is the following:
Look at the last number of the version (x.x.x.1000 in current build). The first part of it is a build number (in this case 100).
Now go to the stable branch of the source https://github.com/YanVugenfirer/kvm-guest-drivers-windows/tree/stable and look for the tags or commit message with message mmXXX <-->bYYY. YYY - will be the external build number (100): https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/8a64980edc9f85dc0f1265827a23f2c053a4821f

Best regards,
Yan.

**Comment by cpatulea** [comment]
Sounds good, thanks.
