### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by thiagocpv** [YanVugenfirer/kvm-guest-drivers-windows#36]
Hi there!

What's the requirements to install in win2008?
How to install the guest drivers?

Thanks.

**Comment by YanVugenfirer** [comment]
Hi,

The package is self contained. Download the package from here and install the driver using device manager either from Windows 2008 or Vista directory: https://fedoraproject.org/wiki/Windows_Virtio_Drivers#Direct_download

Best regards.
Yan.

**Comment by thiagocpv** [comment]
Hi @YanVugenfirer 

Thank you.
