### ISSUE TITLE
Updating balloon.sys to 0.1.96 results in BSOD crash

### ISSUE THREAD

**Issue by opoplawski** [YanVugenfirer/kvm-guest-drivers-windows#39]
I updated my Win 2008R2 system's balloon.sys to 0.1.96 an immediately got a BSOD crash in balloon.sys.  STOP code 0x0000007e and on all subsequent boots.  Disabling the memory balloon device in libvirt for the guest allowed it to boot.

Host is Scientific Linux 6.6, qemu-kvm-0.12.1.2-2.448.el6_6.4.x86_64.

**Comment by YanVugenfirer** [comment]
Hi,

According to Gal (engineer who maintains balloon driver) there were several bugs fixed in the latest build. Please check it - https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.105-1/

Thanks,
Yan.

**Comment by opoplawski** [comment]
That appears to be working better - no crashes.  Haven't tested resizing memory though.  Thanks.
