### ISSUE TITLE
vioscsi loading stucks with uas device on scsi-block

### ISSUE THREAD

**Issue by tomty89** [YanVugenfirer/kvm-guest-drivers-windows#44]
![win10](https://cloud.githubusercontent.com/assets/8604057/10868445/a11f8d12-80c9-11e5-9075-38a4a08d2cfc.png)

When trying to load the vioscsi in Windows 10 installation, the guest stucks at the above stage. It does not freeze though, I can still move the cursor and the progress bar is still going back and forth.

![qemu](https://cloud.githubusercontent.com/assets/8604057/10868446/a8a5b8c2-80c9-11e5-883a-923229cf8848.png)

Then when I try to kill it with ^C, the process turns into some kind of zombie as shown. You can see that it turned into some "qemu-system-x86" which doesn't really exist.

The device is a first gen Intel X25-M SSD connected to USB 3 through a StarTech UAS adapter:
http://ark.intel.com/products/56604/Intel-SSD-X25-M-Series-80GB-2_5in-SATA-3Gbs-50nm-MLC
http://www.startech.com/HDD/Adapters/USB-3-SATA-adapter-cable-with-UASP~USB3S2SAT3CB

I can load vioscsi successfully in the guest if I use the "u" quirk of "usb-storage" in host so that the device does not bind to the uas driver. scsi-hd and viostor works on uas too, just not scsi-block. Also the device never showed any problem when being used physically under Windows or Linux.

I tried that on a Windows Server 2012 R2 (Server version of Windows 8.1) ISO as well, same issue occured.

Feel free to let me know if you need some more other info.

**Comment by tomty89** [comment]
I just tried to install Windows 10 with scsi-block/usb-storage and Arch Linux with scsi-block/uas, both completed without any problem.

**Comment by vrozenfe** [comment]
Hi Tom,
Can you please open a bug through Red Hat Bugzilla portal (https://bugzilla.redhat.com/enter_bug.cgi?product=Virtualization%20Tools), choosing "virtio-win" as "Component". You will need to describe your case and specify kvm and qemu versions. It will help our QE in reproducing the problem.

Thanks,
Vadim Rozenfeld.

**Comment by tomty89** [comment]
Okay done: https://bugzilla.redhat.com/show_bug.cgi?id=1277060

**Comment by YanVugenfirer** [comment]
Thanks!

On Mon, Nov 2, 2015 at 10:59 AM, tomty89 <notifications@github.com> wrote:

> Okay done: https://bugzilla.redhat.com/show_bug.cgi?id=1277060
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/44#issuecomment-152960718>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com
