### ISSUE TITLE
Instructions for w2k needed

### ISSUE THREAD

**Issue by hildred** [YanVugenfirer/kvm-guest-drivers-windows#45]
I cannot find instructions or pointers to documentation for compiling for windows 2000. Firstly what version of ddk is needed? Where can I find it? Alternately are there compiled binaries available?

**Comment by YanVugenfirer** [comment]
Hi,

Unfortunately we removed the ability to build for Windows 2000 several years ago. You might try to see in the history of the repository how to build at least some of the drivers for it (NetKVM had such configuration). You will need pre-Windows 7 DDK, not sure where you can get it officially today.

**Comment by spetr** [comment]
Here you can find WDK 7.1 and it should probably work with Windows 2000 with SP3: https://msdn.microsoft.com/en-us/windows/hardware/hh852365

Windows 2000 with SP3 should also accept drivers for Windows XP.

—
Stanislav Petr
glux@glux.org

**Comment by YanVugenfirer** [comment]
The earliest supported Windows version in Windows 7.1 DDK is XP.

On Tue, Nov 17, 2015 at 12:00 PM, Stanislav Petr <notifications@github.com>
wrote:

> Here you can find WDK 7.1 and it should probably work with Windows 2000
> with SP3: https://msdn.microsoft.com/en-us/windows/hardware/hh852365
>
> Windows 2000 with SP3 should also accept drivers for Windows XP.
>
> —
> Stanislav Petr
> glux@glux.org
>
>
>
> > 17. 11. 2015 v 11:52, Yan Vugenfirer <notifications@github.com>:
> >
> > Hi,
> >
> > Unfortunately we removed the ability to build for Windows 2000 several
> years ago. You might try to see in the history of the repository how to
> build at least some of the drivers for it (NetKVM had such configuration).
> You will need pre-Windows 7 DDK, not sure where you can get it officially
> today.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/45#issuecomment-157324741>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by YanVugenfirer** [comment]
Trying to recall the project history. I think other than NetKVM we never build other drivers for Win2K. For NetKVM you can see the infrastructure for build here: https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/89fa6750423237d30f2d75c498be293144582b53#diff-a217879cec633f8edac899c6b31ebd64

**Comment by YanVugenfirer** [comment]
If you have MSDN subscription, you can download older DDKs from MSDN subscribers downloads. I just checked and they have XP and 2003 DDKs that as far as I recall supported Windows 2000 builds.

**Comment by hildred** [comment]
So I found http://download.microsoft.com/download/9/0/f/90f019ac-8243-48d3-91cf-81fc4093ecfd/1830_usa_ddk.iso which is supoded to be the 2003 ddk. I'll give it a try
