### ISSUE TITLE
NetKVM build problems

### ISSUE THREAD

**Issue by Oloremo** [YanVugenfirer/kvm-guest-drivers-windows#46]
Build Env:
Win 2012 r2, DDK 7.1, WKD 8.1, VS 2013

I'm cloning repo, checkout tag mm131, run builadall.bat from powershell and VirtIO builds fine but NetKVM have errors, here is a build log: [NetKVM-built.txt](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/50740/NetKVM-built.txt)

First error is a CodeAnalize looking in a wrong path:
```
Could not find a part of the path 'C:\Users\Program Files (x86)\Windows Kits\8.1\CodeAnalysis\DriverRecommendedRules.ruleset'
```
Why he looked in Users?..

Second is compile errors:
```
The call to Slamcl returned with exit code:=1.
  This happened while compiling compile.cmd.
  The compile step failed for   'NetKVM' .
EXEC : Compile warning : ** Esp: EspCxxDrv failure (cfg): skipping function '__FallThrough'. [C:\Users\Administrator\Documents\git\kvm\NetKVM\netkvm.vcxproj]
  
EXEC : Compile warning : ** Esp: EspCxxDrv failure (cfg): skipping function '__FallThrough'. [C:\Users\Administrator\Documents\git\kvm\NetKVM\netkvm.vcxproj]
  
EXEC : Compile warning : C:\Program Files (x86)\Windows Kits\8.1\Include\shared\sal.h(2900) : fatal error C1001: An internal error has occurred in the compiler. [C:\Users\Administrator\Documents\git\kvm\NetKVM\netkvm.vcxproj]
  
  SDV exit code: 5
  SDV encountered errors when scanning the driver. Please ensure roletypes are present and/or consult SDV documentation.
C:\Program Files (x86)\Windows Kits\8.1\build\windowsdriver.Sdv.targets(65,9): error MSB3075: The command "staticdv.exe /check" exited with code 5. Please verify that you have sufficient rights to run this command. [C:\Users\Administrator\Documents\git\kvm\NetKVM\netkvm.vcxproj]
Done Building Project "C:\Users\Administrator\Documents\git\kvm\NetKVM\netkvm.vcxproj" (sdv target(s)) -- FAILED.
```

I now sure what wrong here.

P.S. Other drivers build fails too, but I guess source of a problem is same one.

**Comment by YanVugenfirer** [comment]
This is a known issue. It is not a driver build failure but rather the
failure of static driver verifier. We are working with MS to resolve it,
looks like a crash in their tool.

If it really bothers you, exclude "call create_dvl_log.cmd" (should be the
last line) from buildall.bat of NetKVM.

Best regards,
Yan.
