### ISSUE TITLE
virtio input driver

### ISSUE THREAD

**Issue by Flyalay** [YanVugenfirer/kvm-guest-drivers-windows#48]
Hi,
  Do you have plan to implement virtio input driver? 
  Thanks!

**Comment by bendsh** [comment]
Yes, 
    
    I have such a plan.



553538738@qq.com
 
From: 彭谦
Date: 2015-12-25 15:44
To: YanVugenfirer/kvm-guest-drivers-windows
Subject: [kvm-guest-drivers-windows] virtio input drvier (#48)
Hi,
do you have plan to implement virtio input driver? 
Thanks!

**Comment by YanVugenfirer** [comment]
I will be nice! When do you plan start working? Let's sync so we want collide with our effort.

Thanks,
Yan.

**Comment by ladipro** [comment]
Work on a virtio input driver is in progress.
+1 to Yan's comment, please coordinate with us to avoid duplicated efforts.

**Comment by ArseniyShestakov** [comment]
Is there any progress that publicly available?
Would be happy to test it once there will be some code.

**Comment by ladipro** [comment]
Sources should be available in a few weeks. The virtio-input device is "modern-only", meaning that it doesn't support the legacy virtio protocol used by the rest of the virtio-win drivers. So it required a bit of work in the underlying virtio library, which is now being finalized and tested.

**Comment by ladipro** [comment]
The driver lives under /vioinput. Feel free to give it a try and let us know if you run into any issues.
