### ISSUE TITLE
Any plans for virtio-vga device?

### ISSUE THREAD

**Issue by alex3kov** [YanVugenfirer/kvm-guest-drivers-windows#50]
I have no idea if that makes sense, given the existence of QXL - just asking.

**Comment by YanVugenfirer** [comment]
Actually it make a lot of sense for 3D support and local rendering.

But virtio-vga is not in short term plans. On other hand we would be happy
to cooperate with anyone who is ready for the task.

Best regards,
Yan.

On Thu, Jan 14, 2016 at 12:02 PM, Aleksei Kovura <notifications@github.com>
wrote:

> I have no idea if that makes sense, given the existence of QXL - just
> asking
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/50>.
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com
