### ISSUE TITLE
NetKVM driver fails to disable TCP/UDP checksum offloading for IPv6 when host lacks support

### ISSUE THREAD

**Issue by steven676** [YanVugenfirer/kvm-guest-drivers-windows#59]
TCP and UDP communication over IPv6 fails on Windows guests using virtio-net when QEMU is using the userspace networking (slirp) backend.  Adding debug printfs to the slirp code suggests that the guests' transmitted packets are being ignored because of incorrect checksums, and disabling TX checksum offload in the driver settings in Windows allows traffic to pass.

The slirp backend doesn't appear to support checksum offloading, and Linux guests disable checksum offloading accordingly (as verified with ethtool -k).  A quick check of the NetKVM code suggests that the driver does the same thing -- but only for IPv4 (https://github.com/YanVugenfirer/kvm-guest-drivers-windows/blob/master/NetKVM/Common/ParaNdis-Common.cpp#L714); my uninformed guess is that NetKVM needs to disable checksum offloading for TCP/UDP over IPv6 here as well.

Tested most recently with a Windows 10 1511 x64 guest using NetKVM from virtio-win 0.1.113-1 as distributed by Fedora, running on QEMU built from commit 8b4aaba736e55c8ab6d71350f850a6642f0165b9 (after 2.6.0-rc1).  I've had this problem in the past with Windows 7 guests and older versions of the IPv6 userspace networking patch, though.

**Comment by YanVugenfirer** [comment]
Thank you for the report. You are right - of the host doesn't support checksum offloading we should turn this feature off for IPv6 as well.

The fix is simple - to remove IPv6 offload flags from the supported offload features:

`    dependentOptions = osbT4TcpChecksum | osbT4UdpChecksum | osbT4TcpOptionsChecksum |
        osbT6TcpChecksum | osbT6UdpChecksum | osbT6TcpOptionsChecksum | osbT6IpExtChecksum;`

Best regards,
Yan.

**Comment by YanVugenfirer** [comment]
Fixed by: https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/fc983c35687a40bcbdbc5ff5c819a1699a6e4a52
