### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by tobimensch** [YanVugenfirer/kvm-guest-drivers-windows#60]
Hello,

it would be great if you could provide a README.md in this repository.

Are drivers these supposed to be installed on the guest?

Is Windows XP professional supported?

Greetings

**Comment by YanVugenfirer** [comment]
Hello,

Yes those are the Windows guest drivers. We support all the vexations starting from XP up to Windows 10.

Best regards,
Yan.

**Comment by tobimensch** [comment]
Can I mount a 9p filesystem to share folders between host/guest using this or do I need something on top?

**Comment by YanVugenfirer** [comment]
Hi,

Unfortunately virtio-9p is not supported on Windows yet. Gal is working on
it.

Best regards,
Yan.



On Fri, Apr 22, 2016 at 10:47 PM, Tobi <notifications@github.com> wrote:

> Can I mount a 9p filesystem to share folders between host/guest using this
> or do I need something on top?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/60#issuecomment-213566051>
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by tobimensch** [comment]
Thanks for the info. It would be awesome if you guys can get this to work. I'm working on aqemu right now and it would be great if both Linux and Windows guests could use the same method for sharing folders with hosts.

Give a shoutout to Gal from me.

Kind regards!
