### ISSUE TITLE
Question - How to choose a "real stable" code branch？

### ISSUE THREAD

**Issue by zyb521** [YanVugenfirer/kvm-guest-drivers-windows#71]
Hello everyone

I want get the stable branch to building drivers，but which is stable branch, I can't understand it.

The github's stable branch looks updated more frequently than the master, 
and it seems that the latest-virtio package in https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/,  is constructed according to the stable branch code?

Is the stable branch more like a traditional development branch, and the master branch is the "real stable" branch?

I do not know whether my problem is described clearly......

Thank you very much.

**Comment by vrozenfe** [comment]
Yeah, it's a bit confusing.

But you are right, "stable" is mostly reflecting our (Red Hat) internal development and production branch. All binaries in https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/ are
coming from this branch.

Best regards,
Vadim.

**Comment by zyb521** [comment]
thank you vadim.

there is another question,
Last stable-virtio-win version (0.1.102) posted on 2015/04/26 in https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/
Is there a new stable-virtio-win release plan?

**Comment by vrozenfe** [comment]
As a rule we update stable-virtio upon releasing new drivers to the customers. I  believe we will update it soon after releasing next RHEL version.
