### ISSUE TITLE
Crash at 64CPU with virtio net and virtio-win-0.1.102

### ISSUE THREAD

**Issue by alphaonex86** [YanVugenfirer/kvm-guest-drivers-windows#74]
Hello,

Crash:
/usr/bin/qemu-system-x86_64 -drive file=hdd.img,if=virtio,format=qcow2 -k es -alt-grab -m 2048 -vga vmware -net tap,ifname=tap0,script=no,downscript=no -net nic,model=virtio -rtc base=localtime -smp 64,cores=64,sockets=1 -cpu kvm64 -machine q35 -cpu host,+nx -enable-kvm -soundhw hda
No crash:
/usr/bin/qemu-system-x86_64 -drive file=hdd.img,if=virtio,format=qcow2 -k es -alt-grab -m 2048 -vga vmware -net tap,ifname=tap0,script=no,downscript=no -net nic,model=e1000 -rtc base=localtime -smp 64,cores=64,sockets=1 -cpu kvm64 -machine q35 -cpu host,+nx -enable-kvm -soundhw hda
I use the driver found into:
virtio-win-0.1.102.iso

Cheers,

**Comment by YanVugenfirer** [comment]
Hi,

Can you try the latest driver please? 102 was quit experimental one.

If it won't help - could you provide the crash dump?

Thanks,
Yan.

**Comment by alphaonex86** [comment]
It's the last stable branch, have you a link?
How provide you a crash dump?

Thanks

**Comment by YanVugenfirer** [comment]
On Sat, Aug 20, 2016 at 12:02 AM, BRULE Herman <notifications@github.com>
wrote:

> It's the last stable branch, have you a link?
>
Please download latest virtio ISO
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso


> How provide you a crash dump?
>
Please look here (starting from page 30):
http://www.slideshare.net/YanVugenfirer/windows-guestdebugging-kvmforum2012

**Comment by alphaonex86** [comment]
Fixed with virtio-win-0.1.118.iso, thanks
