### ISSUE TITLE
windows 2012 R2 data center blue screen or guest cpu 100% with vitio 62.70.104.8100

### ISSUE THREAD

**Issue by YANGYongqiang** [YanVugenfirer/kvm-guest-drivers-windows#77]
75 and this issue can be reproduced by accessing websites hosted by iis on windows.  Blue screen happens with IRQL_NOT_LESS_OR_EQUAL
 
After blue screen happened, I  upgrade virtio to 0.1.102, but I got another problem described in #75 . When I tried to upgrade virt io to higher version, I encountered the problem described in #76 .

crash dump is attached.
[bluescreen.txt](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/438577/bluescreen.txt)

command rum kvm is ：
/usr/libexec/qemu-kvm -name instance-f37065fc-f948-4d3d-a817-800a376ef5f9 -S -M rhel6.5.0 -cpu SandyBridge,-invpcid,+erms,-bmi2,+smep,-avx2,-bmi1,+fsgsbase,-abm,-pdpe1gb,+rdrand,+f16c,+osxsave,-movbe,+dca,+pcid,+pdcm,+xtpr,-fma,+tm2,+est,+smx,+vmx,+ds_cpl,+monitor,+dtes64,+pbe,+tm,+ht,+ss,+acpi,+ds,+vme -enable-kvm -m 8192 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid f37065fc-f948-4d3d-a817-800a376ef5f9 -smbios type=1,manufacturer=OpenStack Foundation,product=OpenStack Nova,version=2.0.0.28,serial=c9b71027-ac18-4066-a1cc-20c8f90d7b3f,uuid=f37065fc-f948-4d3d-a817-800a376ef5f9 -nodefconfig -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/instance-f37065fc-f948-4d3d-a817-800a376ef5f9.monitor,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime,driftfix=slew -no-kvm-pit-reinjection -no-shutdown -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -drive file=/home/bcc/instances/f37065fc-f948-4d3d-a817-800a376ef5f9/disk,if=none,id=drive-virtio-disk0,format=qcow2,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x4,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -netdev tap,fd=32,id=hostnet0,vhost=on,vhostfd=47 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=fa:16:3e:d7:09:25,bus=pci.0,addr=0x3 -chardev file,id=charserial0,path=/home/bcc/instances/f37065fc-f948-4d3d-a817-800a376ef5f9/console.log -device isa-serial,chardev=charserial0,id=serial0 -chardev pty,id=charserial1 -device isa-serial,chardev=charserial1,id=serial1 -device usb-tablet,id=input0 -vnc 0.0.0.0:12 -k en-us -vga cirrus -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5

**Comment by ladipro** [comment]
Please take a look at this KB:

"0x000000D1" Stop error in Pacer.sys when there's heavy QoS traffic in Windows Server 2012 R2

https://support.microsoft.com/en-us/kb/3101694

**Comment by YANGYongqiang** [comment]
it works. thx.
