### ISSUE TITLE
Win2012_R2 BSOD 0x9F on shutdown when the backend tap device missing and then pausing netkvm in device manager

### ISSUE THREAD

**Issue by zyb521** [YanVugenfirer/kvm-guest-drivers-windows#78]
Hi, every body,

I encountered a problem, windows vm's network is base on ovs and virtio-net.
Is there a way to avoid such problems in the frontend driver?

ths all.

**the dump show:**

> Child-SP          RetAddr           : Call Site
> ffffd000`242cba00 fffff801`68c47b1e : nt!KiSwapContext+0x76
> ffffd000`242cbb40 fffff801`68c475b7 : nt!KiSwapThread+0x14e
> ffffd000`242cbbe0 fffff801`68c703f8 : nt!KiCommitThreadWait+0x127
> ffffd000`242cbc40 fffff801`68cf1462 : nt!KeWaitForSingleObject+0x248
> ffffd000`242cbce0 fffff800`02d26e4d : nt!ExWaitForRundownProtectionReleaseCacheAware+0xaa
> ffffd000`242cbd50 fffff800`006d276e : tcpip!FlPnpEvent+0x1c5
> ffffd000`242cbdc0 fffff800`006d26d3 : NDIS!ndisInvokeNetPnPEvent+0x42
> ffffd000`242cbe00 fffff800`0070e84a : NDIS!ndisDeliverNetPnPEventSynchronously+0x47
> ffffd000`242cbe40 fffff800`006d28f5 : NDIS!ndisPnPNotifyBinding+0x86
> ffffd000`242cbf60 fffff800`006db9cb : NDIS!ndisPnPNotifyBindingUnlocked+0x35
> ffffd000`242cbfb0 fffff800`006db89f : NDIS!ndisPauseProtocolInner+0x6b
> ffffd000`242cc0b0 fffff800`006d0776 : NDIS!ndisPauseProtocol+0x5f
> ffffd000`242cc0f0 fffff800`006d2434 : NDIS!Ndis::BindEngine::Iterate+0x2f6
> ffffd000`242cc300 fffff800`006d1840 : NDIS!Ndis::BindEngine::UpdateBindings+0x64
> ffffd000`242cc330 fffff800`006d2887 : NDIS!Ndis::BindEngine::DispatchPendingWork+0x50
> ffffd000`242cc360 fffff800`0071124f : NDIS!Ndis::BindEngine::ApplyBindChanges+0x33
> ffffd000`242cc3b0 fffff800`006dc2c9 : NDIS!ndisPnPRemoveDevice+0x18b
> ffffd000`242cc600 fffff800`00718b69 : NDIS!ndisPnPRemoveDeviceEx+0x59
> ffffd000`242cc630 fffff800`006d2db6 : NDIS!ndisPnPIrpRemoveDevice+0x8639
> ffffd000`242cc690 fffff801`690675ea : NDIS!ndisPnPDispatch+0x1d2
> 
> kd> !ndiskd.pendingnbls 
> ........
> PHASE 3/3: Found 98 pending NBL(s) of 98 total NBL(s). 
> Search complete.
> 
> kd> !ndiskd.nbl -log ffffcf8003db8df0
>     Allocated
>     MiniportReceived   receive in NDIS, sorting to Opens
>     IndicatedToProtocol ffffcf8003130c10 - TCPIP
>     ProtocolReturned   ffffe000016631a0 - Red Hat VirtIO Ethernet Adapter
>     Freed
>     Allocated
>     ProtocolSent       ffffcf80030f8c70 - QoS Packet Scheduler-0000
>     FilterSent         ffffe000016631a0 - Red Hat VirtIO Ethernet Adapter
>     SentToMiniport     ffffe000016631a0 - Red Hat VirtIO Ethernet Adapter      `//pending in netkvm`

**Steps to reproduce：**
1.start vm into normal Windows
2.delete the backend tap device on host
3.pause the netkvm device in Windows device manager
4.shutdown the Windows vm

**result:**
1. pausing hang in step 3
2. 0x9f bsod on shutdown

**version and config:**
vm virtio-net config xml：

> ```
> <interface type='bridge'>
>   <mac address='00:60:2f:d9:70:2e'/>
>   <source bridge='br0'/>
>   <virtualport type='openvswitch'>
>     <parameters interfaceid='6af6ae68-711b-41ab-a9a9-853c9651c993'/>
>   </virtualport>
>   <target dev='vnet0'/>
>   <model type='virtio'/>
>   <driver name='vhost' queues='4'/>
>   <alias name='net0'/>
>   <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
> </interface>
> ```

**delet tap cmd:** 
ip link delete vnet0

**Comment by YanVugenfirer** [comment]
Hi,

The main reason is probably the packets that were submitted to QEMU but are not completed because backend is gone. The workaround for this can be to hot unplug the device on the guest side through QEMU monitor before removing backend.

Best regards,
Yan.

**Comment by zyb521** [comment]
thks.
