### ISSUE TITLE
[enhancement] Use the WDK instead of the old DDK in the .bat scripts in Win10 branch 

### ISSUE THREAD

**Issue by jean-christophe-manciot** [YanVugenfirer/kvm-guest-drivers-windows#79]
For instance, in VirtIO\buildAll.bat
````
: Use Windows 7 DDK
if "%DDKVER%"=="" set DDKVER=7600.16385.1

: By default DDK is installed under C:\WINDDK, but it can be installed in different location
if "%DDKINSTALLROOT%"=="" set DDKINSTALLROOT=C:\WINDDK\
````

**Comment by ladipro** [comment]
The old DDK is needed for downlevel builds - XP, 2003, Vista, 2008. Even the Win10 branch can still build these targets (for better or worse). Win7+ builds shouldn't require the old DDK to be installed on the system.

**Comment by jean-christophe-manciot** [comment]
Well, it does: I'm unable to run top level buildAll.bat without DDK on a Win10 system. It seems that WDK is useless.

**Comment by ladipro** [comment]
Right - it is currently not possible to run the top level buildAll.bat for only a subset of the targets, it always builds everything for all OSes. If you only want Win10 64-bit drivers for example, run

`buildAll Win10 64`

in \VirtIO

and then

`buildAll Win10 64`

in all driver directories you're interested in. You may need to wait a day or two for a couple of fixes to hit the master branch to make this work (some of the buildAll script currently don't support this kind of selective build).

**Comment by YanVugenfirer** [comment]
Also deleting Win10 branch. It was reintegrated to master several weeks ago.

**Comment by jean-christophe-manciot** [comment]
A few issues have popped up during the build with commit c7471f46c85cd037b973d83df311d5ba02b2f3c4:
```
cd git-kvm-guest-drivers-windows
git checkout master
git reset --hard
git clean -fxd :/
git pull -v --progress --rebase
cd VirtIO
call buildAll.bat Win10 64
cd ..\Balloon
call buildAll.bat Win10 64
cd ..NetKVM
call buildAll.bat Win10 64
cd ..pciserial
call buildAll.bat Win10 64
cd ..pvpanic
call buildAll.bat Win10 64
cd ..vioinput
call buildAll.bat Win10 64
cd ..\viorng
call buildAll.bat Win10 64
cd ..\vioscsi
call buildAll.bat Win10 64
cd ..\vioserial
call buildAll.bat Win10 64
cd ..\viostor
call buildAll.bat Win10 64
````
leads to errors in
- viorng
- vioscsi
- viostor

**Full log**:  [build-kvm-guest-drivers-windows.log.txt](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/463598/build-kvm-guest-drivers-windows.log.txt)

**Comment by ladipro** [comment]
Viorng requires "Windows Cryptographic Provider Development Kit" installed on the build machine.
It is a free download from Microsoft although they ask for personal details and make you agree to stuff because of export restrictions.

I'll look into the SDV build failures in vioscsi and viostor. They can be safely ignored though, these are basically just test builds. You should be able to get rid of the errors by setting the following environment variable before invoking the build scripts:

SET _BUILD_DISABLE_SDV=Yes

**Comment by jean-christophe-manciot** [comment]
Windows Cryptographic Provider Development Kit:
"Unfortunately, the program you are trying to join has been closed. We are sorry for this inconvenience."

**Comment by ladipro** [comment]
That's odd. Try this:
https://www.microsoft.com/en-us/download/details.aspx?id=30688

**Comment by jean-christophe-manciot** [comment]
That's much better than the link I tried from technet.
The "WCPDK" **clears the build of all previously mentioned errors**, except for a few ones with balloon that I've previously overlooked because they are not counted as such:
```
makeinstall Win10 x64 balloon
**Could Not Find** C:\Users\ActionMystique\Virtio\git-kvm-guest-drivers-windows\Balloon\Install\Win10\amd64\balloon.*
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
The system **cannot find the file specified**.
"Setting OS mask for:" Win10 x64
.........................
Signability test complete.

Errors:
None

Warnings:
None

Catalog generation complete.
C:\Users\ActionMystique\Virtio\git-kvm-guest-drivers-windows\Balloon\Install\Win10\amd64\balloon.cat
The **system cannot find the path specified**.
... repeated multiple times
```
They are strange; I've checked the path "**C:\Users\ActionMystique\Virtio\git-kvm-guest-drivers-windows\Balloon\Install\Win10\amd64\balloon.cat**": it does exist.
Under the **git bash terminal**:
```
ActionMystique@KVM-Windows-10 MINGW64 ~/Virtio/git-kvm-guest-drivers-windows/Balloon/Install/Win10/amd64 (master)
$ ll
total 932
-rw-r--r-- 1 ActionMystique 197611   1291 Sep 10 19:08 balloon.cat
-rw-r--r-- 1 ActionMystique 197611   2717 Sep 10 19:08 balloon.inf
-rw-r--r-- 1 ActionMystique 197611 905216 Sep 10 19:08 balloon.pdb
-rwxr-xr-x 1 ActionMystique 197611  38400 Sep 10 19:08 balloon.sys*
```
Under **Windows terminal**:
```
C:\Users\ActionMystique\Virtio\git-kvm-guest-drivers-windows\Balloon\Install\Win10\amd64>dir
 Volume in drive C has no label.
 Volume Serial Number is 5CC5-52BC

 Directory of C:\Users\ActionMystique\Virtio\git-kvm-guest-drivers-windows\Balloon\Install\Win10\amd64

09/10/2016  07:08 PM    <DIR>          .
09/10/2016  07:08 PM    <DIR>          ..
09/10/2016  07:08 PM             1,291 balloon.cat
09/10/2016  07:08 PM             2,717 balloon.inf
09/10/2016  07:08 PM           905,216 balloon.pdb
09/10/2016  07:08 PM            38,400 balloon.sys
               4 File(s)        947,624 bytes
               2 Dir(s)  23,958,167,552 bytes free
```

**Comment by jean-christophe-manciot** [comment]
Full log: 
[build-kvm-guest-drivers-windows.log.txt](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/465532/build-kvm-guest-drivers-windows.log.txt)

**Comment by ladipro** [comment]
This can be safely ignored. Win10 driver doesn't come with the WDF coinstaller but Balloon/sys/packOne.bat is still trying to copy it over. I'll have it fixed shortly. Thanks!

**Comment by ladipro** [comment]
The "could not find / cannot find" errors should be gone as of commit a31ef68

**Comment by ladipro** [comment]
Closing now. If you run into more build issues, please don't hesitate to report them. Thanks!
