### ISSUE TITLE
windows 2012 R2 data center BSOD with 0x7f netkvm.sys

### ISSUE THREAD

**Issue by YANGYongqiang** [YanVugenfirer/kvm-guest-drivers-windows#80]
stack trace from dump is pasted bellow.

It also happens with netkvm 0.1.118

RetAddr           : Args to Child                                                           : Call Site
00 fffff802`b1d68de9 : 00000000`0000007f 00000000`00000008 fffff802`b335fe70 fffff802`b3350f80 : nt!KeBugCheckEx
01 fffff802`b1d66ef4 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiBugCheckDispatch+0x69
02 fffff802`b1eacd01 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiDoubleFaultAbort+0xb4
03 fffff802`b1cddb6a : 00000000`00000000 00000000`00000001 00000000`00000200 00000000`00000010 : nt!ExAllocatePoolWithTag+0x2b1
04 fffff800`dbf1145e : 00000000`00000000 00000000`00000001 ffffe001`2f286000 00000000`00000000 : nt!ExAllocatePoolWithTagPriority+0x6a
05 fffff800`dbf0fc2d : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : netkvm+0xd45e
06 fffff800`dace3632 : ffffe001`39984310 00000000`00000000 00000000`00000000 00000000`00000000 : netkvm+0xbc2d
07 (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : NDIS!ndisMSendNBLToMiniportInternal+0xe7
08 fffff800`dace38c0 : 00000000`00000000 00000000`00000000 ffffe001`39984310 00000000`00000000 : NDIS!ndisMSendNBLToMiniport+0xf2
09 fffff800`dacdc9bd : 00000000`00000051 ffffe001`39984310 ffffe001`2f54dc70 fffff800`dbce70c5 : NDIS!ndisInvokeNextSendHandler+0x40
0a (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : NDIS!ndisFilterSendNetBufferLists+0x2b3
0b fffff800`dbce5f5b : ffffe001`39984310 00000000`00000000 fffff802`b3351390 ffffe001`39984310 : NDIS!NdisFSendNetBufferLists+0x2ed
0c fffff800`dbcdc695 : ffffe001`39984310 00000000`00000000 00000000`00000000 00000000`00000001 : pacer!PcpLineSendNetBufferLists+0x1fb
0d fffff800`dbce2987 : ffffe001`2f20b010 fffff802
[Uploading bluescreen.txt…]()
`b3351479 00000000`00000001 00000000`00000000 : pacer!PcpSchedulerBatchAndSendOrDropNblChain+0x89
0e fffff800`dbcdb850 : 00000006`3bab7e01 00000000`00369e01 ffffe001`2f20d2d0 ffffe001`2f20b010 : pacer!PcpTimeoutHandler+0x2ab
0f (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : pacer!PcpIndicateTimerUnitConsumerEnd+0x357e
10 (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : pacer!PcpSignalExternalEventEnd+0x357e
11 fffff800`dacdceee : ffffe001`00000001 00000000`00000000 00000000`00000001 fffff800`dbf0cc00 : pacer!PcFilterSendNetBufferListsComplete+0x37b0
12 (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : NDIS!ndisCallSendCompleteHandler+0x5
13 (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : NDIS!ndisIterativeDPInvokeHandlerOnTracker+0x374
14 (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : NDIS!ndisInvokeNextSendCompleteHandler+0x434
15 (Inline Function) : --------`-------- --------`-------- --------`-------- --------`-------- : NDIS!ndisMSendNetBufferListsCompleteInternal+0x494
16 fffff800`dbf0ef25 : ffffe001`2f2741a0 ffffe001`3508a830 ffffe001`320349e8 00000008`9edf0a3e : NDIS!NdisMSendNetBufferListsComplete+0x4de
17 fffff800`dbf1137d : ffffe001`2f286000 ffffe001`2f286000 ffffe001`00000000 ffffe001`2f2f1001 : netkvm+0xaf25
18 fffff800`dbf11be8 : ffffe001`2f286000 ffffe001`2f286001 ffffe001`2f286000 00000000`00000042 : netkvm+0xd37d
19 fffff802`b23a1a37 : 00000000`00000018 00000000`00000000 ffffe001`33965ed8 ffffe001`33965ea0 : netkvm+0xdbe8

fffff800`dbf04000 fffff800`dbf20000   netkvm     (no symbols)  
    Loaded symbol image file: netkvm.sys
    Image path: \SystemRoot\system32\DRIVERS\netkvm.sys
    Image name: netkvm.sys
    Browse all global symbols  functions  data
    Timestamp:        Tue Apr 29 21:44:50 2014 (535FACD2)
    CheckSum:         0001E80D
    ImageSize:        0001C000
    Translations:     0000.04b0 0000.04e4 0409.04b0 0409.04e4

**Comment by YanVugenfirer** [comment]
Hello,

I suggest to use version 126. We fix several issues after 118.

Best regards,
Yan.
