### ISSUE TITLE
Windows choose wrong driver

### ISSUE THREAD

**Issue by ggzengel** [YanVugenfirer/kvm-guest-drivers-windows#82]
Because there is no OS specific declaration in the inf file windows choose the wrong driver and will show BSOD.
If you use TargetOSVersion decoration this won't happen any more:
https://msdn.microsoft.com/en-us/windows/hardware/drivers/install/inf-manufacturer-section

Without this changes it's very difficult (or not possible) to deploy windows with WDS/DSHARE and a single driver store.

With this its should also be possible to have a multi OS inf file and put all drivers for one device in a single path.

**Comment by ggzengel** [comment]
Is it possible to compile a single driver for multiple OSs:
https://msdn.microsoft.com/en-us/windows/hardware/drivers/develop/building-drivers-for-different-versions-of-windows
https://msdn.microsoft.com/en-us/library/windows/hardware/ff554887

The risk to take the wrong driver on installing/updating is to big.
Since years I haven't seen BSOD on installing/updating drivers and I always choose to search the whole CD or package or put all into DSHARE.

I just migrate from Hyper-V to KVM and injected all viostore drivers with DISM.
W2K-R2 was booting, found depended hardware and showed BSOD after rebooting.
If if inject only the right driver windows will reboot without errors.

If I install balloning drivers with searching the whole subdirectories (or choose the wrong driver by mistake) I will get a BSOD instantly.

**Comment by ladipro** [comment]
Thanks for reporting this. TargetOSVersion has already been added to .inf (for example cbb63c3 for viostor) and will be part of the next build. It should be available soon, please stay tuned.

I'll close this now, please follow https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/8

I realize that I wrote "a build should be out soon" there, apologies for taking so long.
