### ISSUE TITLE
64-bit drivers miscompiled

### ISSUE THREAD

**Issue by nbuwe** [YanVugenfirer/kvm-guest-drivers-windows#87]
While investigating VirtualBox bug https://www.virtualbox.org/ticket/16248 I was puzzled by the inconsistent behaviour of the driver (0.1.126).  Logs (correctly) claimed that MSI was not found, yet the driver accessed device config at the offset 24, not 20, as if MSI support were present.

Eventually this was tracked down to what appears a miscompilation.  The call to `virtio_device_initialize(..., pContext->bUsingMSIX ? true : false);` sets only the least significant byte of `r9` with `setne r9b`.  But `virtio_device_initialize` operates on the whole register, including any garbage in the upper bytes `mov esi, r9d; ... mov dword ptr [rbp+8], esi;` and then later in `vio_legacy_get_config` it also does `cmp dword ptr [rcx+8], 0` for the `vdev->msix_used` check.

I wonder if you inadvertently compile different parts of the code with different definition of `bool`.

**Comment by ladipro** [comment]
> I wonder if you inadvertently compile different parts of the code with different definition of bool.

Indeed, it's a C vs C++ bool definition mismatch. Yuri recently fixed it in

https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/bccbfb90b9680854a0656054582ced13683f3abd

Thanks!
