### ISSUE TITLE
netkvm BSOD 0x9f with multiple NICs plugin on win2008r2

### ISSUE THREAD

**Issue by zyb521** [YanVugenfirer/kvm-guest-drivers-windows#89]
hi everyone,

there is a netkvm 0x9f bsod when continuous hot plugin nics using virsh tool and then shutdown windows.  this is a probability event, our virtio-win is based 102, and also appeared 126.

it looks like netkvm driver take a lot of time on alloc shared memory in ParaNdis6_Initialize during windows shtudown.

I have two question:
1.from MSDN, shared memory used for nic driver with DMA, For the virtual nic driver, Is this still necessary?
2.Is there a way to avoid initialization and shutdown conflicts in the netkvm code?

thanks all.

**dump core info:**
> DRIVER_POWER_STATE_FAILURE (9f)
> A driver has failed to complete a power IRP within a specific time.
> Arguments:
> Arg1: 0000000000000004, The power transition timed out waiting to synchronize with the Pnp
> 	subsystem.
> Arg2: 0000000000000258, Timeout in seconds.
> Arg3: fffffa83b1472040, The thread currently holding on to the Pnp lock.
> Arg4: fffff88001e29510, nt!TRIAGE_9F_PNP on Win7 and higher
> 
> 1: kd> !thread fffffa83b1472040
> THREAD fffffa83b1472040  Cid 0004.0054  Teb: 0000000000000000 Win32Thread: 0000000000000000 RUNNING on processor 4
> Not impersonating
> DeviceMap                 fffff8a000008b30
> Owning Process            fffffa83b1409890       Image:         System
> Attached Process          N/A            Image:         N/A
> Wait Start TickCount      52855          Ticks: 1 (0:00:00:00.015)
> Context Switch Count      881899         IdealProcessor: 0  NoStackSwap
> UserTime                  00:00:00.000
> KernelTime                00:10:15.343
> Win32 Start Address nt!ExpWorkerThread (0xfffff800018e7910)
> Stack Init fffff880021d0db0 Current fffff880021cf760
> Base fffff880021d1000 Limit fffff880021cb000 Call 0
> Priority 12 BasePriority 12 UnusualBoost 0 ForegroundBoost 0 IoPriority 2 PagePriority 5
> Child-SP               RetAddr               : Call Site
> fffff880`021cfcb0 fffff800`019ac318 : nt!MiPfnsWorthTrying+0x10c
> fffff880`021cfce0 fffff800`019e6e5d : nt!MiFindContiguousPages+0xb18
> fffff880`021cfe00 fffff800`019e7e73 : nt!MiAllocateContiguousMemory+0x22d
> fffff880`021cfe90 fffff800`018182a0 : nt!MmAllocateContiguousMemorySpecifyCache+0x53
> fffff880`021cfed0 fffff880`00f0837a : hal!HalAllocateCommonBuffer+0x40
> fffff880`021cff10 fffff880`02cd6449 : NDIS!NdisMAllocateSharedMemory+0x1aa
> fffff880`021cff70 fffff880`02cced57 : netkvm!ParaNdis_InitialAllocatePhysicalMemory+0x21
> fffff880`021cffb0 fffff880`02ccf042 : netkvm!CParaNdisRX::CreateRxDescriptorOnInit+0xb7
> fffff880`021cffe0 fffff880`02ccec97 : netkvm!CParaNdisRX::PrepareReceiveBuffers+0x4e
> fffff880`021d0010 fffff880`02ccbeaa : netkvm!CParaNdisRX::Create+0x7b
> fffff880`021d0050 fffff880`02cca3ed : netkvm!ParaNdis_VirtIONetInit+0x3de
> fffff880`021d00a0 fffff880`02cd4979 : netkvm!ParaNdis_FinishInitialization+0x7d
> fffff880`021d00f0 fffff880`00f02de5 : netkvm!ParaNdis6_Initialize+0x485
> fffff880`021d0270 fffff880`00f02683 : NDIS!ndisMInitializeAdapter+0x695
> fffff880`021d0630 fffff880`00f0476c : NDIS!ndisInitializeAdapter+0x113
> fffff880`021d0690 fffff880`00f02356 : NDIS!ndisPnPStartDevice+0xac
> fffff880`021d06f0 fffff800`01c9417e : NDIS!ndisPnPDispatch+0x246
> fffff880`021d0790 fffff800`019cab2d : nt!PnpAsynchronousCall+0xce
> fffff880`021d07d0 fffff800`01ca34c6 : nt!PnpStartDevice+0x11d
> 
> 1: kd> !locks
> **** DUMP OF ALL RESOURCE OBJECTS ****
> KD: Scanning for held locks..
> 
> Resource @ nt!IopDeviceTreeLock (0xfffff80001ad9540)    Shared 1 owning threads
>      Threads: fffffa83b1472040-01<*> 
> KD: Scanning for held locks.
> 
> Resource @ nt!PiEngineLock (0xfffff80001ad9440)    Exclusively owned
>     Contention Count = 9
>     NumberOfExclusiveWaiters = 2
>      Threads: fffffa83b1472040-01<*> 
>      Threads Waiting On Exclusive Access:
>               fffffa83b143db60       fffffa83b4158060       
> 
> KD: Scanning for held locks..
> 
> Resource @ NDIS!SharedMemoryResource (0xfffff88000ebd030)    Exclusively owned
>      Threads: fffffa83b1472040-01<*> 
> KD: Scanning for held locks............................................................................................................................
> 4046 total locks, 3 locks currently held

test script：
```
for((i=0;i<16;i++))
do
    date
    virsh attach-device $vms vif.xml
    sleep 1
done
sleep 20
virsh shutdown $vms
```

**Comment by ybendito** [comment]
Regarding memory allocations - yes, the driver shall allocate physical memory, the device is 'virtual' only from host perspective.
As we can see from the dump data, the problem caused by OS PnP activity which does not allow power flow to execute. So, at least at first glance it does not have simple solution in the driver. Which device parameters used for created devices (does the vif.xml contain queues/mq parameters)? What is reproduction rate (100% or less)? Which delay in the script (instead of 20) solves the problem?

**Comment by zyb521** [comment]
ybendito, thank you very much for your reply.

In this test, attach device with 4 queues, and the reproduction rate is about 20%, increasing the stress of cpu/memory using BurnInTest on the vm will make it easier to reproduce.

vif.xml
>     <interface type='bridge'>
>       <source bridge='br0'/>
>       <virtualport type='openvswitch'/>
>       <model type='virtio'/>
>       <driver name='vhost' queues='4'/>
>     </interface>


The delay in the script is not very useful, from the vm's qemu log, each net device take 30s~120s or more time to complete the initialize,  we can get console port remove log but not get the nic remove log on poweroff.

> qemu log:
> 2016-12-29T11:17:20.891514+08:00|info|qemu[8494]|[8595]|virtio_set_status[719]|: virtio-net device status is 1 that means ACKNOWLEDGE
> 2016-12-29T11:17:20.891588+08:00|info|qemu[8494]|[8595]|virtio_set_status[719]|: virtio-net device status is 3 that means DRIVER
> 2016-12-29T11:17:46.751520+08:00|info|qemu[8494]|[8494]|handle_control_message[351]|: virtio serial port '2' hanle control message event = 6, value = 0
> 2016-12-29T11:17:46.751655+08:00|info|qemu[8494]|[8494]|monitor_qapi_event_emit[479]|: {"timestamp": {"seconds": 1482981466, "microseconds": 751580}, "event": "VSERPORT_CHANGE", "data": {"open": false, "id": "channel1"}}
> 2016-12-29T11:17:46.751852+08:00|info|qemu[8494]|[8494]|handle_control_message[351]|: virtio serial port '1' hanle control message event = 6, value = 0
> 2016-12-29T11:17:46.752059+08:00|info|qemu[8494]|[8494]|monitor_qapi_event_emit[479]|: {"timestamp": {"seconds": 1482981466, "microseconds": 752011}, "event": "VSERPORT_CHANGE", "data": {"open": false, "id": "channel0"}}
> 2016-12-29T11:18:29.032644+08:00|info|qemu[8494]|[8595]|virtio_set_status[719]|: virtio-net device status is 7 that means DRIVER OK
> 2016-12-29T11:18:29.036374+08:00|info|qemu[8494]|[8595]|monitor_qapi_event_emit[479]|: {"timestamp": {"seconds": 1482981509, "microseconds": 36275}, "event": "NIC_RX_FILTER_CHANGED", "data": {"name": "net2", "path": "/machine/peripheral/net2/virtio-backend"}}
> 2016-12-29T11:18:29.056957+08:00|info|qemu[8494]|[8597]|virtio_set_status[719]|: virtio-net device status is 1 that means ACKNOWLEDGE
> 2016-12-29T11:18:29.057010+08:00|info|qemu[8494]|[8597]|virtio_set_status[719]|: virtio-net device status is 3 that means DRIVER
> 2016-12-29T11:20:23.398316+08:00|info|qemu[8494]|[8597]|virtio_set_status[719]|: virtio-net device status is 7 that means DRIVER OK
> 2016-12-29T11:20:23.416768+08:00|info|qemu[8494]|[8598]|monitor_qapi_event_emit[479]|: {"timestamp": {"seconds": 1482981623, "microseconds": 416681}, "event": "NIC_RX_FILTER_CHANGED", "data": {"name": "net3", "path": "/machine/peripheral/net3/virtio-backend"}}
> 2016-12-29T11:20:23.429154+08:00|info|qemu[8494]|[8595]|virtio_set_status[719]|: virtio-net device status is 1 that means ACKNOWLEDGE
> 2016-12-29T11:20:23.429238+08:00|info|qemu[8494]|[8595]|virtio_set_status[719]|: virtio-net device status is 3 that means DRIVER
> 2016-12-29T11:23:00.738150+08:00|info|qemu[8494]|[8598]|virtio_set_status[719]|: virtio-net device status is 7 that means DRIVER OK
> ....  
> .... //hang here and 0x9f bsod

**Comment by fengmin75** [comment]
NDIS on Windows Server 2008R2 does have issue on memory allocation. With a lot of memory alloc in a row, it's getting slower and slower. If you configure VM with multi-queue and large queue size, it can get 10+ minutes to just initialize the queue.

One work around is to allocate a large chunk of memory at a time to speed up the allocation time. Check out the link below for the patch. It's still pending for merge. 

https://github.com/YanVugenfirer/kvm-guest-drivers-windows/pull/30/commits/c9b113eaf621dbb926b17694902847da13752b6a

**Comment by zyb521** [comment]
@fengmin75  thank you very much.
I have try the patch on my code, It can speed up the initialization, but can not completely solve my problem, the probability of 0x9F bsod is reduced, and vm shutdown takes 7~8 minutes.

This problem does not reproduce on 2012r2, perhaps a really bug on 2008r2. 
:-)
