### ISSUE TITLE
How to create iso & sign all driver after compile

### ISSUE THREAD

**Issue by morphinz** [YanVugenfirer/kvm-guest-drivers-windows#92]
Hello.   
I'm using the issue for asking question sorry for that.
  
1- Is there any tool "take all compiled drivers together && sign all drive && create iso" or i need to do that manualy? I found the repo "https://github.com/crobinso/virtio-win-pkg-scripts" but couldn't figure out usage.  
2- After compile i couldn't find Server drivers like in "virtio.iso". I have "Win7, Win8, Win8.1, Win10, wlh, Wnet, Wxp"
3- Should i run "buildAll.bat" with any parameters like "release".
4- Can we run the "BuildAll.bat" any faster way? Like "windows parallel build".
5- Can i install the drivers with "non-registered certificate" without "windows testsigning on"?

**Comment by YanVugenfirer** [comment]
Hi,

1. There are some internal tools that many users of the drivers created. What we have  only the first part (build all the drivers). The sign part relates to the question #5 - you can use internal certificate (needs "Windows testsining on)) - or you need certificate provided by signing authority or MS signed drivers.

2. Because Windows uses the same kernel for server and client SKUs, there us a mapping for those:

WinXP - Windows Server 2003
Went - this is a code name for Windows Server 2003
wlh, which is an old code name Windows Longhorn for Windows Server 2008
Win 7 - Windows Server 2008R2
Win 8 - Windows Server 2012
Windows 8.1 - Windows Server 2012R2
Windows 10 - Windows Server 2016

3. No really, it will build release drivers by default

4. You could split the build for each platform to separate script and run it in parallel

5. Answered in 1.

Best regards,
Yan.

**Comment by morphinz** [comment]
Thank you for your answer and this awesome job. 

Okay than this means: there is no way to install without "testsigning on" and i can't install drivers at windows installation. 
I have to create "ide disk", after installation i can change drivers with "testsigning". 
This is really bad because my all arch must changed now..
Windows should change this policy or publish a test signature for developers.

___________________________
I'm giving my Windows driver installation batch script for other users.
This scripts will Recognize your Windows version and Arc. You can import your test drivers with this easy way. 
```
@echo off

:: BatchGotAdmin
:-------------------------------------
REM  --> Check for permissions
IF '%PROCESSOR_ARCHITECTURE%' EQU 'amd64' (
   >nul 2>&1 "%SYSTEMROOT%\SysWOW64\icacls.exe" "%SYSTEMROOT%\SysWOW64\config"
 ) ELSE (
   >nul 2>&1 "%SYSTEMROOT%\system32\icacls.exe" "%SYSTEMROOT%\system32\config"
)

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params = %*:"=""
    echo UAC.ShellExecute "cmd.exe", "/c ""%~s0"" %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    pushd "%CD%"
    CD /D "%~dp0"
:--------------------------------------  
echo Certificates importing..
echo off
".\Tools\certmgr.exe" -add Tools\testDrivers.cer -s -r localMachine ROOT
".\Tools\certmgr.exe" -add Tools\testDrivers.cer -s -r localMachine TRUSTEDPUBLISHER
echo Import ok

bcdedit /set testsigning on

setlocal
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto Windows-10
if "%version%" == "6.3" goto Windows-81
if "%version%" == "6.2" goto Windows-8
if "%version%" == "6.1" goto Windows-7
if "%version%" == "6.0" goto Windows-Vista
rem etc etc
endlocal

:Windows-10
if "%PROCESSOR_ARCHITECTURE%"=="AMD64" goto 1064BIT
else
echo Windows 10-x86 Drivers installing..
pnputil -a ".Network\Win10\x86\netkvm.inf"
echo Installed.
goto end
:1064BIT
echo Windows 10-x64 Drivers installing..
pnputil -a ".\Network\Win10\amd64\netkvm.inf"
echo Installed.
:end
pause
```

**Comment by YanVugenfirer** [comment]
Thanks for sharing!

"Okay than this means: there is no way to install without "testsigning on" and i can't install drivers at windows installation."
You still can get certificate from one of the signing authorities. Also drivers that are distributed with  Fedora are signed with official Red Hat certificate: https://fedoraproject.org/wiki/Windows_Virtio_Drivers#Direct_download
