### ISSUE TITLE
vioserial driver init failed with no msi support

### ISSUE THREAD

**Issue by zyb521** [YanVugenfirer/kvm-guest-drivers-windows#94]
hi everyone,
    I install vioserial driver failed on win7 32bit. 
    It's seem a init bug with no msi support.

thanks all.

some error info(include my debug print):
![image](https://cloud.githubusercontent.com/assets/5163063/22773360/b53de6e0-eedc-11e6-925f-e5b29a465393.png)

bug code:
```
    /* set up the device config vector */
    msix_vec = PCIGetMSIInterruptVector(pWdfDriver->ConfigInterrupt);
    if (virtio_set_config_vector(&pWdfDriver->VIODevice, msix_vec) != msix_vec) {
		DbgPrint("virtio: zyb xxxxxx, msix_vec %u\n", msix_vec);
        return STATUS_DEVICE_BUSY;
    }
```

others info:
virtio-win-0.1.130
win7 sp1 pro 32bit

**Comment by ladipro** [comment]
Hi, can you please check what the virtio_set_config_vector() call returns?

```
new_vec = virtio_set_config_vector(&pWdfDriver->VIODevice, msix_vec);
if (new_vec != msix_vec) {
  DbgPrint("virtio: zyb xxxxxx, msix_vec %u %u\n", new_vec, msix_vec);
  ...
```

Thanks!

**Comment by zyb521** [comment]
@ladipro  that return is 0

![image](https://cloud.githubusercontent.com/assets/5163063/22775089/0b8c92b4-eee5-11e6-89cc-b1cbc8d56334.png)

**Comment by ladipro** [comment]
Thanks, that's really odd. Looking at the QEMU code, the MSI vector returned by reading VIRTIO_MSI_CONFIG_VECTOR can only be VIRTIO_NO_VECTOR (65535) or the value written to it previously.

Does this repro with a vanilla Win7 32 bit and the driver distributed in virtio-win-0.1.130 or did you do something to disable MSI? What version of QEMU are you on? Thanks!

**Comment by zyb521** [comment]
@ladipro thanks for your reply.

I confirmed that is a bug.

First, I found this bug with the compile code form virtio-win-0.1.130-1.src.rpm, and i reproduced it with binary files form virtio-win-0.1.130.iso, so i add some log just as you see.

I have try both win7 32bit and win7 sp1 32bit, and by using virtio-win-0.1.126, vioserial install succ. 

thanks.

**Comment by ladipro** [comment]
I can reproduce this by setting MSISupported to 0. Either by tweaking the driver inf, or after installing it by editing the registry manually.

HKLM\SYSTEM\CurrentControlSet\Enum\PCI\VEN_1AF4&DEV_1003&SUBSYS_00031AF4&REV_00\3&13c0b0c5&0&28\Device Parameters\Interrupt Management\MessageSignaledInterruptProperties

Also, confirming that it is a regression. After 126 the driver unconditionally sets config and queue interrupt vectors, previously it would not do it if MSI was disabled.

**Comment by ladipro** [comment]
Fixed in commit: https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/a528eb6e6790675a33f3612cca31462264d19a58

@zyb521, many thanks for reporting this!
